server:
  port: 7010
spring:
  application:
    name: lab-zuul
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7000/eureka
zuul:
  routes:
    sponsor:
      path: /ad-sponsor/**
      serviceId: ad-sponsor
      strip-prefix: false
  prefix: /laboratory

