server:
  port: 7010
spring:
  application:
    name: lab-zuul
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7000/eureka
zuul:
  routes:
    order:
      path: /order/**
      serviceId: lab-order
    user:
      path: /user/**
      serviceId: lab-user
      sensitive-headers:
      custom-sensitive-headers: true
