server:
  port: 7021
  servlet:
    context-path: /ad-search
spring:
  application:
    name: ad-search
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    show-sql: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/laboratory?autoReconnect=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    tomcat:
      max-active: 4
      min-idle: 2
      initial-size: 2
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/

feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"