server:
  port: 8905
spring:
  application:
    name: lab-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gf-huanchupk/SpringCloudLearning/
          search-paths: respo
          username:
          password:
      label: master